### ISSUE TITLE
libcudnn - Error

### ISSUE THREAD

**Issue by Q-si** [pavelzbornik/whisperX-FastAPI#31]
When I try to perform a transcription using the Swagger Page API, I get the following error:

Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

Any idea where the problem is and how to solve it?

**Comment by jhj0517** [comment]
Trying to update `faster-whisper` and `torch` might help:
```
pip install -U faster-whisper torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
```

( This assumes that you're using CUDA 12.4 ), 
This happens because there's a strict version matrix between CTranslate2 and torch : https://github.com/SYSTRAN/faster-whisper/issues/1086

**Comment by Q-si** [comment]
`nvidia-smi` is showing me `Driver Version: 550.120` and `CUDA Version: 12.4 `. But i am not able to build a Docker Container that works :(
Can someone push a Container to hub.docker.com?

**Comment by Q-si** [comment]
I've added "ctranslate2==4.4.0" at the end of the file requirements.txt
It seems to work now.
